In [5]:
import numpy as np
import math


# Defining NumPy Arrays
Arrays are essentially lists, or lists of lists

numpy arrays can only be numeric (int or float)

In [9]:
# a list can be made into a one-dimensional array
ar1 = np.array([1,2,3])
print ("ar1 has {} dimension".format(ar1.ndim))

#a list of lists makes a two-dimensional array
ar2 = ([4,5,6])
ar12 = np.array([ar1, ar2])
print ("ar12 is a list of lists and has {} dimensions".format(ar12.ndim))
ar12

ar1 has 1 dimension
ar12 is a list of lists and has 2 dimensions


array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# you can interrogate the number of elements in each direction using the np.shape property
ar12.shape

(2, 3)

In [18]:
# you can interrgate the type of data in the array 
ar3 = np.array([1.2, 3.14, 5])
ar3.dtype
# only integers and floats are recognized
# numpy will try to make the array homogenous, that is all one type, thus if an integer value is combined with a float the entire array will be float

dtype('float64')

In [24]:
# if you know the shape but not the contents of the array, you can set up the structure of the array with zeroes,ones, or random numbers as placeholders
ar4= np.ones([2,3])
ar5= np.zeros([2,4])
ar6 = np.random.rand(3,2)
print(ar4)
print(ar5)
print(ar6)


[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.86588169 0.60667023]
 [0.41479258 0.15872529]
 [0.47038051 0.37586051]]


In [39]:
# you can also fill arrays with ranges of values using the arange() (careful, that is not 'arrange') function and the linspace() function
#arange takes 3 parameters begin value, end value, and step
ar7 = np.arange(0,100,5)
print('ar7 array:{}'.format(ar7))
# when defining and array with the arange() function, the first value is inclusive and the last value is exclusive

# linspace() also has 3 parameters, but the third parameter is not the step value as in arange, but rather the total number of items you want to generate
ar8 = np.linspace(1,2,5)
print ("ar8 has 5 items to get from 1 to 2: {}".format(ar8))


ar7 array:[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
ar8 has 5 items to get from 1 to 2: [1.   1.25 1.5  1.75 2.  ]


# NumPy Array Operations


In [45]:
# arithmetic operators on arrays apply elementwise
a = np.arange(10,50,10)
b = np.arange(1,5,1)
c = a+b
print(a)
print(b)
print(c)
print(d)

# arithmetic operation on arrays that are not the same shape cause an error 
d = np.arange(1,4,1)
print(a.shape)
print (d.shape)
e = a+d
print(e)


[10 20 30 40]
[1 2 3 4]
[11 22 33 44]
[1 2 3]
(4,)
(3,)


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [54]:
# when you apply a function to an array, it applies the function to every element of the array
# say, for example you have an array of centimeters measurments and you want convert these to inches
# there are 2.54 centimeters in an inch
centimeters = np.array([1,2,3,4])
inches = centimeters / 2.54
print (centimeters)
print (inches)

[1 2 3 4]
[0.39370079 0.78740157 1.18110236 1.57480315]


In [56]:
#if you apply a boolean test it will apply the test to all elements of the array and return an array filled with boolean values
# for example testing if the inches are greater than 1
print (inches)
more_than_one = inches>1
print (more_than_one)

[0.39370079 0.78740157 1.18110236 1.57480315]
[False False  True  True]


0.39370078740157477