In [1]:
import re
import numpy as np
import math

In [3]:
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)
print ("re.findall returns a list of strings")

['bat', 'bot']
re.findall returns a list of strings


In [28]:
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result
a= np.ones([20,20])
b= np.zeros([20,20])
# a= np.reshape(a,(20*20))
# b= np.reshape(b,(20*20,1))
# a
# b
print (l2_dist(np.reshape(a, (20*20)), np.reshape(b,(20*20,1))))
print (l2_dist(np.reshape(a, (20*20)), np.reshape(b,(20*20))))
print(l2_dist(a,b))
print (l2_dist(a.T,b.T))

400.0
20.0
20.0
20.0


In [49]:
a1 = np.random.rand(4)
a2 = np.random.rand(4,1)
a3 = np.array([[1,2,3,4]])
a4 = np.arange(1,4,1)
a5 = np.linspace(1,4,4)

print (a1)
print(a1.shape)
print (a2.shape)
print(a1.shape == a2.shape)
print (a5)
print(a5.shape)
print (a5.shape == a1.shape)
print(a4.shape)
print (a3.shape ==a4.shape)
print(a3)
print (a3.ndim)
a4=np.arange(1,4,1)
print(a4.ndim)
print(a4)


[0.66225953 0.09972478 0.13847966 0.49232411]
(4,)
(4, 1)
False
[1. 2. 3. 4.]
(4,)
True
(3,)
False
[[1 2 3 4]]
2
1
[1 2 3]


In [53]:
old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0
print(old)
new[1,2:]= 15
print(old)


[[0 0 1]
 [1 1 1]]
[[ 0  0  1]
 [ 1  1 15]]


In [63]:
# [2:4,2:4]
ar = np.arange(0,36,1)
print (ar)
ar.shape = (6,6)
print (ar)
sub_ar = ar[2:4,2:4]
print (sub_ar)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[14 15]
 [20 21]]


In [72]:
import re
s = 'ACBCAC'
print(re.findall('^AC',s))


['AC']


In [78]:
import re

s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
print(result)
# L = len(result)

['A', 'AA', 'AA', 'AA', 'A']


In [86]:
data = 'Office of Research Administration: (734) 647-6333 | 4325 North Quad Office of Budget and Financial Administration: (734) 647-8044 | 309 Maynard, Suite 205 Health Informatics Program: (734) 763-2285 | 333 Maynard, Suite 500 Office of the Dean: (734) 647-3576 | 4322 North Quad UMSI Engagement Center: (734) 763-1251 | 777 North University Faculty Adminstrative Support Staff: (734) 764-9376 | 4322 North Quad'

print(re.findall('[(]\d{3}[)]\s\d{3}[-]\d{4}',data))

['(734) 647-6333', '(734) 647-8044', '(734) 763-2285', '(734) 647-3576', '(734) 763-1251', '(734) 764-9376']


In [89]:
data = "I refer to https://google.com and I never refer http://www.baidu.com if I have to search anything"
print(re.findall('(?<=[https]:\/\/)([A-Za-z0-9.]*)',data))

['google.com', 'www.baidu.com']


In [91]:
text=r'''Everyone has the following fundamental freedoms:
(a) freedom of conscience and religion;
(b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
(c) freedom of peaceful assembly; and
(d) freedom of association.
'''
print(len(re.findall('\(.\)', text)))

4
